ESX Bridge
ND-Framework/ND_MDT pull request #20
Opened 2024-04-22 18:01 UTC by Maximus7474

All systems should be functional, I've tested them to the best extent with a single client.
Some features are harder to integrate by default because it depends what the end user uses/configures on his server, this includes:
- Billing System for fines
- Changing ID Images
- Getting the User's phone number

The property system is based of esx_property, but as for the phone and billing I'll try to add custom functions and integrations for these in `bridge/esx/shared.lua`

2024-04-22 21:36 UTC, Filcatalao requested changes

2024-04-22 21:36 UTC, Filcatalao commented on bridge/esx/database/alterESX-DB.sql
> +INSERT INTO `esx-legacy-scripting-server`.`items` (`name`, `label`, `weight`, `rare`) VALUES ('mdt-tablet', 'Mobile Data Terminal', 2, 1);
Schema should not be here

2024-04-23 19:41 UTC, Maximus7474 commented
I'm an idiot for not checking everything, issue with late night development.
Hold the PR for the moment

2024-04-23 19:54 UTC, Maximus7474 commented
Fixed and Checked again

2024-09-24 18:05 UTC, pokameni commented
I use it on my server. Just had to do one modification because my server doesn't have this only isBoss callback. Just had to verify by another way.

```
function Bridge.getPlayerInfo()
    local xPlayer = ESX.GetPlayerData() or {}

    local isBoss = false
    if (xPlayer.job ~= nil and xPlayer.job.grade_name == "boss") or 
       (xPlayer.job2 ~= nil and xPlayer.job2.grade_name == "boss") then
        isBoss = true
    end

    local img = profilePicture or lib.callback.await("ND_MDT:esx:getProfileImage", false)
    if img ~= profilePicture then
        profilePicture = img
    end

    return {
        firstName = xPlayer.firstName or "",
        lastName = xPlayer.lastName or "",
        job = xPlayer?.job?.name or "",
        jobLabel = xPlayer.job?.label or "",
        job2 = xPlayer?.job2?.name or "",
        job2Label = xPlayer.job2?.label or "",
        callsign = xPlayer?.metadata?.callsign or "",
        img = img,
        isBoss = isBoss,
    }
end
```

Anyway good job.

2024-09-24 20:38 UTC, Maximus7474 commented
Well, I understand your approach but base ESX doesn't have dual jobs so it wasn't integrated for that reason 😅

2024-10-24 22:46 UTC, Andyyy7666 commented
Thank you for your contribution @Maximus7474, I've been MIA from FiveM but I'll now review this and merge. If I remember correctly esx had job grades maybe that can be used to determine if the player is a high enough rank.

2024-10-25 20:02 UTC, Maximus7474 commented
Hey Andy,

No probs at all, thought so. I'm not quite sure anymore what other stuff I've changed on it since.
Job grades in esx are number based, so you can quite easily define a hierarchy in that way.

2025-02-01 21:18 UTC, merged

2025-02-01 21:18 UTC, Andyyy7666 commented
Merged so ppl can use, will fix eventual issues that come up and probably work on a rewrite on the mdt.

2025-02-02 11:10 UTC, Maximus7474 commented
Forgot this one still existed 😂 no probs can follow up if any issues are opened up, think this was worked on esx 1.10 something not sure anymore